apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: optimizationpolicies.engineops.hummbl.dev
spec:
  group: engineops.hummbl.dev
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                policyName:
                  type: string
                targetNamespace:
                  type: string
                objectives:
                  type: array
                  items:
                    type: string
  scope: Namespaced
  names:
    plural: optimizationpolicies
    singular: optimizationpolicy
    kind: OptimizationPolicy
    shortNames:
      - optpol
