apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: engine-ops-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/hummbl-dev/engine-ops.git
    targetRevision: HEAD
    path: infra/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
